### ISSUE TITLE
add `pctl` cli as package to Homebrew package manager

### ISSUE THREAD

**Issue by sharan-rafay** [paralus/cli#25]
### Briefly describe the feature

- add this CLI tool in Homebrew package manager which is widely used by Mac users. Adding to their repo will give more visibility to the wide userbase. [brew.sh](https://brew.sh/)

### What problem does this feature solve? Please link any relevant documentation or Issues

- having tool in package manager like `brew` will make installation process easy

### _(optional)_ What is your current workaround?

- NONE

**Comment by rustiever** [comment]
Hey @meain @niravparikh05 can we use this to release the CLI [Goreleaser](https://goreleaser.com/)

**Comment by meain** [comment]
@rustiever We already make use of goreleaser [ref](https://github.com/paralus/cli/blob/495cbe77acddea032b2213a91f56b10826d41516/.github/workflows/release.yml#L39). :D

**Comment by rustiever** [comment]
in that case can we add support to ship the package to homebrew since goreleaser supports it.

**Comment by meain** [comment]
That could be an option, but should we consider contributing to upstream or should we just manage a tap on our end?

**Comment by rustiever** [comment]
i think `gorelease` has only homebrew tap support, if we are okay with tapping, can i work on this?

**Comment by meain** [comment]
What `goreleaser` does is that it generated the ruby file needed to package this, which we can either push to a tap that we own(goreleaser can do this automatically) or we can contribute this to upstream homebrew if we want to make it more discoverable. I guess we can start with creating a custom tap in the org and start from there, but I'll leave the final decision up to @niravparikh05 if we want to do that or wait a little while and contribute it to upstream homebrew.

**Comment by sharan-rafay** [comment]
i like tapping first in org, then we'll push to upstream. Let me know which approach to take @niravparikh05 @meain
