### ISSUE TITLE
Creating project scoped role failed

### ISSUE THREAD

**Issue by akshay196** [paralus/cli#27]
### Expected vs actual behavior
Actual:
```
$ ./pctl create role test-role --scope project --permissions project.read,cluster.read,partner.read,organization.read --config ./admin@paralus.local.json 
Error: invalid permissions, error: invalid permission partner.read  
$ ./pctl create role test-role --scope project --permissions project.read,cluster.read,organization.read --config ./admin@paralus.local.json 
Error: invalid permissions, error: invalid permission organization.read
```
Should be able to create role with "partner.read" permission.
We are able to create "project" scoped role with "partner.read" permission from the Paralus console.

### Steps to reproduce the bug
Run above steps.

### Are you using the latest version of the project?

You can check your version by running `helm ls|grep '^<deployment-name>'` or using [pctl](https://github.com/paralus/cli), `pctl version`, and provide the output.

-

### What is your environment setup? Please tell us your cloud provider, operating system, and include the output of `kubectl version --output=yaml` and `helm version`. Any other information that you have, eg. logs and custom values, is highly appreciated!

```
VERSION: 0.1.0
BUILD: 0.1.0
BUILD-TIME: 1656329967
ARCH: linux/amd64
```

### _(optional)_ If you have ideas on why the bug happens or how it can be solved, please provide it here

-

- [X] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [X] I'm using the latest version of the project.

**Comment by akshay196** [comment]
@niravparikh05 There is discrepancy between dashboard and CLI tool. Can you verify which one is correct method to create a role?

**Comment by niravparikh05** [comment]
both partner and organization read roles are required irrespective of the scoped role creation. partner and organization read roles are currently scoped at organization level and hence added these to scoped role permission list service.
