### ISSUE TITLE
pctl upgrade via CLI

### ISSUE THREAD

**Issue by techmaharaj** [paralus/cli#35]
### Briefly describe the feature
Currently whenever there's a new release of pctl, the user needs to manually download and update the pctl binary in their system. Since it doesn't automatically install while installing Paralus, the user may miss out on updating pctl.

We could have a command like `pctl upgrade --latest` which basically downloads the latest binary for the current system and installs it. 

We could also have a background check for latest version when the user types pctl. If there's a newer version, it can display a sentence like 'you're using an outdated version of pctl, please upgrade to the latest binary'

### What problem does this feature solve? Please link any relevant documentation or Issues
Makes the pctl upgrade process easier and faster.

**Comment by akshay196** [comment]
@techmaharaj It would be nice to have such feature in pctl. Although it comes with challenges in pctl upgrading itself. pctl can be installed using multiple ways on different OS/platforms like downloading binary to $PATH, brew package manager on MacOS, running in Docker container. To upgrade itself, first we need to understand its installation technique and perform necessary actions.
Although user can manage pctl upgrade by themself whenever required. Using the third-part package managers for installation is recommended those has upgrade procedure within it.
I understand currently pctl can be installing by downloading binary for Linux machines. In future we could package it for different package managers like apt, dnf etc.

**Comment by niravparikh05** [comment]
Closing this as we are not planning to pick it up, if you still foresee this adding immense value please raise a separate issue.
